server:
  port: 8085

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

